citizenlab/test-lists

- lists/services/meek/meek.csv
This was submitted by dcf via mail.
> Add URLs used by Tor's meek pluggable transport.

- lists/et.csv
> Missing comma and the end of row.

- lists/00-proposed-category_codes.csv
> edited typos

- lists/zw.csv
> add zimbabwe testing list

- lists/et.csv
+ versions (https/http) based on recent observations of political events in ET
> Adding more relevant urls for ET

- lists/ae.csv
Added comas in the last 2 rows, between "sources" and "notes" - as suggested here: https://github.com/citizenlab/test-lists/issues/88.
> Minor edit based on git issue #88

- lists/fr.csv
Hi,
Here are some first domains to be tested in France.
> Add specific tests for France

- lists/global.csv
I've reviewed all of the URLs included in the global test list and have made the following main changes:
1. Deleted pornographic websites that aren't highly ranked on Alexa.
2. Deleted websites that are squatted/removed/no longer exist/dead.
3. Replaced old domains with their current versions.
4. Added HTTPS to sites that now support HTTPS and load with it automatically when the user accesses them from a normal browser.
> Updated/Reviewed the Global test list

- lists/global.csv
I've added the following URLs to the global test list:
1. https://www.frontlinedefenders.org/
2. https://tacticaltech.org/
3. https://bouncer.ooni.io (to see if OONI's bouncer is blocked)
> Added URLs to global test list

- scripts/lint-lists.py
Prior to this change, only one of all the exceptions would be printed when linting the list.
Now it will gather all the errors and print them all out.
> Improve the list linting script

- lists/az.csv
This pull request includes 4 independent media sites that were recently reported to be blocked in AZ.
> Added blocked media sites to AZ test list

- lists/mm.csv
Just added a site (http://www.bestbuy.com/) that was reported to be inaccessible in Myanmar.
> Added site to MM test list

- lists/az.csv
I updated the AZ test list to include the following sites:
cumhuriyyet.net (NEWS MEDIA)
gununsesi.info (NEWS MEDIA)
dosye.org (NEWS MEDIA)
24saat.org (NEWS MEDIA)
irfs.org (HUMAN RIGHTS)
> Added sites to the AZ test list

- lists/ir.csv
The Iranian test list has been updated thanks to URLs provided from the folks at ASL19. However, the categories probably require some review, since I added them myself (based on Google translations...not being a Farsi speaker). A review of the categories would be much appreciated!
> Updated Iranian test list

- lists/eg.csv
Three news sites (added their work-around aliases too), one human rights site, and [bridges.]torproject.org
> somemore over the past two days

- lists/eg.csv
add 4 blocked websites in Egyptian list eg.csv,  depended on AFTE's List: https://afteegypt.org/right_to_know-2/publicationsright_to_know-right_to_know-2/2017/06/04/13069-afteegypt.html?lang=en
> add 4 blocked websites in eg.csv

- lists/pk.csv
I updated the PK test list to add a URL that has been reported to be blocked locally.
> Updated PK test list

- lists/global.csv
Hi,
I'm adding this two website to the global list as I think it's worth to know if the A/I services are censored and if so in which country
* http://autistici.org/
* http://noblogs.org/
bye
> adding autistici and noblogs

- lists/zw.csv
The Zimbabwean test list has been updated with URLs provided by the Digital Society of Zimbabwe.
> Updated ZW test list

- lists/az.csv
Added 2 more sites to the AZ test list that were recently reported to be blocked.
> Updated AZ test list

- lists/global.csv
- lists/ir.csv
As part of this pull request I:
1. Edited some category codes in the Global and IR test lists (some categories were wrong)
2. Updated the IR test list to include URLs (and their respective category codes) that we found to be blocked in Iran based on ooniprobe tests
> Updated IR and Global test lists

- lists/global.csv
- lists/ir.csv
I replaced "MISC" in the Global and IR test lists with all their respective categories, and I changed category codes that appeared to be wrong (across both lists).
> Cleaned up the Global and IR test lists

- lists/global.csv
Fixes #214 
Cross-reference:
https://github.com/TheTorProject/ooniprobe-android/issues/106
https://github.com/TheTorProject/ooniprobe-android/pull/107
> Fixes url for gay.com

- lists/ch.csv
`appel-au-peuple.org` are blocked by upc
```sh
pi@raspberrypi:~ $ nslookup appel-au-peuple.org 62.2.17.60
Server:		62.2.17.60
Address:	62.2.17.60#53
Non-authoritative answer:
Name:	appel-au-peuple.org
Address: 212.142.33.184
pi@raspberrypi:~ $ nslookup appel-au-peuple.org 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53
Non-authoritative answer:
Name:	appel-au-peuple.org
Address: 162.255.119.46
```
---
`freejustice.de` are blocked by upc and swisscom
```sh
pi@raspberrypi:~ $ nslookup freejustice.de 62.2.17.60
Server:		62.2.17.60
Address:	62.2.17.60#53
Non-authoritative answer:
Name:	freejustice.de
Address: 212.142.33.184
markus@kari:~$ nslookup freejustice.de 195.186.1.111
Server:		195.186.1.111
Address:	195.186.1.111#53
Non-authoritative answer:
Name:	freejustice.de
Address: 195.186.135.218 …
```
> add some domains to ch.csv list

- lists/global.csv
It has been reported that the OTF site has been blocked in various countries around the world, and so it's being added to the global test list.
> Added OTF site to Global test list

- lists/ir.csv
Added a news site upon request from the community.
> Added news site to IR test lst

- lists/dz.csv
This PR includes 2 URLs that have reportedly been blocked in Algeria.
> Updated DZ test list

- lists/ng.csv
This PR includes a number of domains that were recently reported to be blocked in Nigeria.
Sources: https://pinigeria.org/president-buharis-secret-war-on-free-speech/ & http://www.itrealms.com.ng/2017/11/leaked-ncc-writes-telco-to-block-21-pro.html
> Updated Nigerian test list

- lists/ng.csv
I've added a URL that is reportedly blocked in Nigeria.
> Added URL to NG list

- lists/ru.csv
Added a few sites that are reportedly blocked in Russia and which have been ordered to get blocked.
> Updated RU test list

- lists/global.csv
The sci-hub.ac domain was just blocked. This pull request adds sci-hub.bz, which is not yet blocked.
> Add https://sci-hub.bz/

- lists/ua.csv
Added URLs from the Presidential Order number 133/2017 that indicates a list of organizations to be sanctioned in Ukraine. Sanctions include blocking of websites. The full document and the list of websites is accessible here: http://www.president.gov.ua/storage/j-files-storage/00/40/38/6f76b8df9d0716da74bb4ae6a900d483_1494964345.pdf
> updated ua list

- lists/tr.csv
https://anticapitalist.party/@accedie/99345033281811972
> Add anticapitalist.party for testing in turkey, per blocking report

- lists/cd.csv
We now have a new test list for the DRC thanks to URLs provided by community members.
> Created new test list for the DRC

- lists/ss.csv
This pull request includes URLs for the South Sudan test list as provided by community members.
> Updated SS test list

- lists/global.csv
I've added protonmail to the global test list because community members reported that it seems to be blocked in some countries.
> Added protonmail to global test list

- lists/ec.csv
This is a starting set just to begin gathering data from Ecuador.
> This file lists the URLs to test from Ecuador.

- lists/uy.csv
Created an initial list of websites for Uruguay. I hope is not too small.
> Initial list for Uruguay. Created after court order to block Roja Directa

- lists/et.csv
I have added a Zone 9 blog to the ET list that's reportedly blocked in Ethiopia.
> Added a URL to the ET list

- lists/kz.csv
Updated the KZ test list based on URLs provided by community members. I have also deleted some dead URLs.
> Updated KZ test list

- lists/pk.csv
Added a site that's reportedly blocked in Pakistan.
> Updated PK list

- README.md
This PR adds the citation method @willscott drafted in issue  #111 to the README.
> Added preferred citation method to README

- lists/eg.csv
I have updated the EG test list to include a site that's reportedly blocked.
> Updated EG list

- lists/ng.csv
I updated the Nigerian test list based on some research.
> Updated NG test list

- lists/cm.csv
I've started a new test list for Cameroon, particularly with elections coming up. Contributions are appreciated!
> New Cameroon test list

- lists/th.csv
- add Thai political party urls
- few news media and political criticism sites
> Add Thai political party urls

- lists/global.csv
This adds a few of the major cryptocurrency exchanges, and bootstrap / entry points to bitcoin and ethereum networks.
* The bitcoin entry points use DNS lookups from hard-coded dns names [in the source](https://github.com/bitcoin/bitcoin/blob/863e995b79ec388bf292d80f181912d01e20e2e5/src/net.cpp#L1128)
* In addition, DNS and IP based reachability would complement that, but is out of scope for this list.
* Infura is the most popular web gateway for submitting transactions into ethereum, and is a reasonable proxy for whether there is interference with that network.
* The others are a global selection of the largest exchanges listed on [wikipedia](https://en.wikipedia.org/wiki/Cryptocurrency_exchange)
There have already been reports of cryptocurrencies being blocked by countries. Seems worth …
> Cryptocurrency monitoring

- lists/bd.csv
I've added all the active sites listed in this article: 
https://www.thedailystar.net/country/news/btrc-withdraws-block-58-sews-sites-1671769
> updated bangladesh local list

- lists/cd.csv
added new organizations and media in connection with the upcoming elections
> added new organizations and media

- lists/cm.csv
- lists/ve.csv
Updated the VE & CM test lists to include URLs reportedly blocked.
> Updated VE & CM test lists

- lists/py.csv
Hello, Tedic propose this Paraguayan list.
> Tedic's proposed list

- scripts/lint-lists.py
The `fix_slashes` and `fix_duplicates` methods are pretty useful to cleanup test lists and it's best to expose them as arguments.
While I was at it I also ported the script over to python3. It should still work with python2, but that is EOL in a year from now anyways.
> Add support for python3 and expose fix_duplcates & fix_slash as args

- lists/in.csv
India's 2019 general elections start in 2 days so I updated the IN test list to include a number of missing political party sites. I tried to include as many of those participating in the 2019 elections as possible, but not all political parties seem to have functional websites (and some don't appear to have websites at all). I also added several election-specific websites.
@hellais @sneft I'd appreciate it if you could please review & merge in time for the elections. Thanks for your time!
> Updated IN test list

- lists/uy.csv
It is adding news website to the list and adding some of the websites from https://github.com/citizenlab/test-lists/pull/87/ .
> Updating websites from Uruguay to test for censorship.

- lists/ir.csv
To test the hypothesis: "comparison of encrypted content for specific URL censorship in HTTPS"
> add some instagram URLs to ir.csv

- lists/am.csv
- lists/az.csv
- lists/be.csv
- lists/by.csv
- lists/ch.csv
- lists/dz.csv
- lists/ee.csv
- lists/fr.csv
- lists/gt.csv
- lists/kg.csv
- lists/lv.csv
- lists/ma.csv
- lists/md.csv
- lists/ru.csv
- lists/tn.csv
- lists/ua.csv
- lists/uz.csv
Update the French-speaking countries list with fr.wikisource.org and fr.m.wikisource.org, and Russian-speaking countries with ru.wikisource.org and ru.m.wikisource.org
> Update Wikisource URLs

- lists/ir.csv
Related to https://github.com/citizenlab/test-lists/pull/484#discussion_r311192551
> Add termux.org and termux.net to ir.csv

- lists/ir.csv
After checking the links in OONI explorer, I noticed that most of the tests received "URL signature expired" message. And this shows that in Instagram, the URLs of the files change periodically. Therefore, that hypothesis cannot be true for these URLs.
cc: @agrabeli @hellais
> Remove some URLs related to PR  #472

- lists/global.csv
> add archive.is to global.csv

- lists/ug.csv
I added a blog (covering LGBTQI issues) that's reportedly inaccessible in Uganda (and potentially blocked). I also added the site of the human rights organization led by the author of the (reportedly blocked) blog.
> Updated UG test list

- lists/cz.csv
This list contains gambling sites blocked by Czech ISP on the basis of the regulation by Ministry of Finance of the Czech Republic
> Czech Republic censorship list

- lists/ni.csv
Reverts citizenlab/test-lists#528
See https://github.com/citizenlab/test-lists/pull/528#issuecomment-545164054 for an explanation as to why.
> Revert "Removed blank Nicaragua list (.ni) "

- lists/by.csv
https://en.wikipedia.org/wiki/Lurkmore
> testing how Lurkmore it blocked in Belarus

- lists/pk.csv
This PR includes updates to the PK test list by Netalitica researchers.
> Netalitica updates to PK test list

- lists/cn.csv
- lists/global.csv
See: https://www.coindesk.com/chinas-internet-firewall-has-blocked-access-to-ethereum-block-explorer-etherscan-io
> Add ethereum related sites blocked in china to the global and CN lists

- lists/az.csv
Reported blocked by qurium: https://www.qurium.org/alerts/azerbaijan/gununsesi-org-blocked-in-azerbaijan/
> Add gununsesi.org to AZ country list

- lists/tm.csv
This PR includes TM test list updates by Netalitica researchers.
> Netalitica updates to TM test list

- lists/uz.csv
This PR includes updates to the UZ test list by Netalitica researchers.
> Netalitica updates to UZ test list

- lists/jo.csv
This PR includes JO test list updates by Netalitica researchers.
> Netalitica updates to JO test list

- lists/cn.csv
This PR includes updates to the CN test list by Netalitica researchers.
> Netalitica updates to CN test list

- lists/et.csv
Thanks to URLs shared by local community members, we have updated the ET test list to include more LGBTQI sites.
> Added more LGBTQI sites to ET test list

- lists/global.csv
- Anonymization and circumvention tools
https://www.uproxy.org/ `#4,919,659`
https://getlantern.org/ `#84,982`
https://massbrowser.cs.umass.edu/
- Social Networking
https://joinmastodon.org/ `#97,279`
https://mastodon.social/ `#27,011`
> Updated Global test list

- lists/ir.csv
We have been informed by community members that certain gambling websites are particularly risky to test in Iran, so in this PR I remove them from the IR test list (as the risk of testing them is likely greater than the value of confirming their blocking -- particularly since it is already widely known that gambling sites are blocked in Iran).
> Updated IR test list

- lists/kz.csv
This PR includes updates to the KZ test list by Netalitica researchers.
> Netalitica updates to KZ test list

- lists/th.csv
- Add few links
- Update redirect/https links
- Remove obsoleted links, dead links, domain expired, domain changed owners, etc.
https://mobgunmai.com/
http://www.pic2010.org/
https://twitter.com/somsakjeam
https://thisrupt.co/
- http://bangkok.coconuts.co/ --> https://coconuts.co/bangkok/
- http://www.searo.who.int/ --> https://www.who.int/southeastasia
- http://www.nationmultimedia.com/ --> https://www.nationthailand.com/
- http://www.iias.nl --> https://www.iias.asia/
- http://www.greenpeace.or.th --> https://www.greenpeace.org/thailand/
- http://www.fridae.com/ -> https://www.fridae.asia/
- http://www.foreignaffairs.org/ -> https://www.foreignaffairs.com/
- http://www.asiasoft.co.th/ -> https://www.asiasoft.net/
- http://www.atimes.com/se-asia/se-asia.html -> https://asiatimes.com/
- …
> Update Thailand test list

- lists/au.csv
Fixes https://github.com/citizenlab/test-lists/issues/231
> Add URL to Australia list

- lists/ae.csv
- lists/global.csv
- lists/ir.csv
- lists/sa.csv
Maybe we should remove this domain parking page?
> Remove http://www.stupidcensorship.com/ (domain parking page).

- lists/global.csv
Normalise URL to the one without www.
> Remove duplicate protonmail entry

- lists/global.csv
- lists/sa.csv
These URLs were shared by OutRight Action International.
> Updated SA & Global test lists with LGBTQI sites

- lists/au.csv
- lists/be.csv
- lists/global.csv
This PR includes updates to the global test list based on URLs shared by a community member, which I categorized. 
I added one of those URLs to the BE test list (since it seemed more country-specific).
> Updated the global test list

- lists/es.csv
Blocked at least at Vodafone, usign Allot it's become usual. "Por causas ajenas a Vodafone, esta web no está disponible"
> [ES] Add a torrent sharing website

- lists/global.csv
Public domain site targeted by copyright extremists
> add project Gutenberg

- lists/es.csv
This PR adds a reproduction rights site to the ES test list which may be blocked.
> Added abortion site to ES test list

- lists/tr.csv
Arabic websites reportedly blocked over geopolitics added to TR test list, thanks to updates by Netalitica researchers.
> Netalitica updates to TR test list

- lists/az.csv
Added mirror sites of blocked media websites in Azerbaijan.
> Added mirror sites to AZ test list

- lists/th.csv
Updates to the TH test list by Netalitica researchers.
> Netalitica updates to TH test list

- lists/ir.csv
(Introducing tools and tutorials that will be useful in Internet shutdown.)
> add irandarkhamooshi

- lists/cu.csv
Updated the CU test list to add a media site reportedly blocked (and to add the HTTPS version of DDC).
> Updated CU test list

- lists/lb.csv
As part of this PR, I've added a site to the LB test list that has been blocked based on a court order. See: https://twitter.com/shinmimlam/status/1287663590275600384
> Updated LB test list

- README.md
it can be written as more than one or more country
> improve docs 

- lists/jo.csv
Added protonvpn.com and https://alurdunyya.net/
> Update Jordan test list

- lists/co.csv
Thanks to the great work of Netalitica researchers, the CO test list has been updated extensively.
> Netalitica updates to CO test list

- lists/lb.csv
Thanks to the great work of Netalitica researchers, 92% of the LB test list has been updated.
> Netalitica updates to LB test list

- lists/hk.csv
Added HK site reportedly blocked according to 
* https://twitter.com/KwongGlacier/status/1347176882664443909
* https://twitter.com/lokmantsui/status/1347196360735346691
Probably worth having on list.
> added hk chronicles

- lists/hk.csv
Adding https://hkleaks.info/ which is reportedly blocked in HK too.
> Updated HK test list

- lists/global.csv
> add YouTube and Picasa image hosting addresses

- lists/global.csv
The Play Store and App Store are reportedly blocked in Uganda. I figured it's probably worth having them tested globally, which is why I added relevant links to the global test list.
> Add app store links to Global test list

- lists/mm.csv
Added Open Data portals that are reported blocked. 
/cc @agrabeli
> Added Myanmar/Mekong Open Data Portals

- lists/fr.csv
This site is alleged to be blocked. It may be a good idea to add it to other Francophone lists as well.
> Add Démocratie Participative

- lists/global.csv
Community members are reporting that Clubhouse may be blocked in the UAE. I'm opening this PR to add the Clubhouse site to the global test list, since it probably deserves global testing.
> Added clubhouse to global test list

- lists/sn.csv
Just added a media website which is reportedly being interfered with in Senegal.
> Added media to SN test list

- lists/global.csv
NordVPN appears to be blocked in Myanmar (based on OONI measurements), but it's worth testing globally.
> Added NordVPN to global test list

- lists/eg.csv
- lists/ps.csv
The EG and PS test lists included VPN sites that I just added to the global test list (https://github.com/citizenlab/test-lists/pull/736). I am therefore removing them from the country lists.
> Removed duplicates (with global) from country lists

- lists/global.csv
These are taken from a list of banned (in Myanmar) VPNs that circulated on Facebook: https://www.facebook.com/groups/yesagyogp/permalink/1119533741827118/
These VPN sites should probably get tested globally.
> Added more VPN sites to global test list

- lists/by.csv
The specific page why most likely these stats about people beaten by police
https://mediazona.by/article/2020/10/13/minsk-beaten
> Another blocked resource in Belarus

- scripts/lint-lists.py
This also makes `lint-lists.py` executable.
> Explain why URL is invalid when lint fails

- lists/mm.csv
Added some URLs of MM government sites that were missing from the local list.
> Added some missing mm gov sites

- lists/global.csv
> Remove sayhichat.com

- lists/il.csv
In light of the situation in Palestine, I think it would be interesting to check whether Palestinian news websites and human rights sites are being censored in Israel. I have therefore updated the IL test list accordingly (while also adding a few Israeli news websites). 
As this seems high priority for testing, it would be great if we could merge this PR asap.
> Updated the IL test list

- lists/my.csv
This PR includes extensive updates to the MY test list by Netalitica researchers.
> Netalitica updates to MY test list

- lists/global.csv
> Remove dead URL

- lists/global.csv
> Remove www.womensmediapool.org

- lists/global.csv
Down since https://web.archive.org/web/20180324210936/http://radioislam.org/
> Remove www.radioislam.org

- lists/co.csv
This site seems to be blocked in Colombia: https://explorer.ooni.org/measurement/20210526T144001Z_webconnectivity_CO_10299_n1_zbVsOokykR7sSM3n?input=https%3A%2F%2Fghostbin.co%2F
https://explorer.ooni.org/measurement/20210526T144001Z_webconnectivity_CO_10299_n1_zbVsOokykR7sSM3n?input=https%3A%2F%2Fghostbin.co%2Fpaste%2F8ds6u9%2Fraw
> Added ghostbin to CO test list

- lists/kh.csv
This PR includes updates to the KH test list based on URLs shared by community members.
> Updated KH test list

- lists/global.csv
Would you please add GlobaLeaks to the list?
Thank you if you could
> Add GlobaLeaks

- lists/global.csv
Reference: https://en.wikipedia.org/wiki/AskMoses.com
Fixes OpenObservatory/ooni-resources#22, fixes ooni/probe#1712
> Remove defunct askmoses.com

- lists/th.csv
All Government-run websites (GOVT)
will close #821
> Add Ministry of Public Health and COVID-19 urls

- lists/hk.csv
Adding [8962museum.com](https://8964museum.com/)
> Updating Hong Kong list

- lists/kw.csv
Ref: https://upper-hand.org/269/
> Add upper-hand.org

- lists/in.csv
This PR includes many new contributions to the IN test list by participants of a 2-day test list workshop organized by India's Bachchao Project.
> Updates to IN test list from Bachchao Project workshop

- lists/global.csv
> Removed http://www.whitepower.com/

- lists/cn.csv
- lists/global.csv
> Removed http://www.lyricwiki.org/ & https://twitpic.com/

- lists/global.csv
> Removed http://www.law-lib.utoronto.ca/Diana/

- lists/global.csv
> Removed http://www.iwantim.com/

- lists/global.csv
> Removed http://www.interactworldwide.org/

- lists/global.csv
> Removed http://www.atimes.com/

- lists/global.csv
> Removed http://www.talafone.com/

- lists/global.csv
> Removed http://www.roulette.sh/

- lists/global.csv
> Removed http://www.kazaa.com/

- lists/global.csv
> Removed http://www.jfcom.mil/

- lists/global.csv
> Removed http://www.jdl.org/

- lists/global.csv
> Removed http://www.ginvodka.org/

- lists/global.csv
> Removed http://www.fring.com/

- lists/global.csv
> Removed http://www.emule.com/

- lists/global.csv
> Removed http://www.efonica.com/

- lists/global.csv
> Removed http://www.dmoz.org/ & http://lifestream.aol.com/

- lists/global.csv
> Removed http://www.convertingtojudaism.com/ & http://www.religiousconsultation.org/

- lists/global.csv
> Removed http://www.blubster.com/

- lists/global.csv
> Removed http://www.arabrenewal.com/

- lists/global.csv
> Removed https://sci-hub.tw/

- lists/global.csv
Removed https://addons.mozilla.org/en-US/firefox/addon/4286
> Firefox add-on that is no longer available

- lists/global.csv
> Removed http://del.icio.us/ & http://de.lirio.us/

- lists/bd.csv
Is reddit in the main list? If it is, will remove it.
> bd.csv list, Follow on from #809

- lists/ir.csv
This PR is based on https://github.com/citizenlab/test-lists/pull/645, excluding a media site which is already included in the Global test list.
> Blocked gaming sites added to IR test list

- lists/ug.csv
I propose changes to the test list for Uganda, to enable us to collect data on specific action that might be taken against news sites. Most local news sites were already reflected on the list, but not regional or international outlets.
> Proposed updates to Uganda test list to include regional and global news sites

- lists/global.csv
I did a bit of clean-up to the Global test list, updating some URLs to HTTPS, and removing a few URLs that are known to (almost always) cause false positives.
A more extensive clean-up and update to the Global test list is needed.
> Updates to Global list

- lists/th.csv
Add https://www.no112.org/ a signature collection website to propose the end of the lese majeste law (Article 112).
Reported to be blocked since 15 Feb 2022
https://www.matichon.co.th/news-monitor/news_3185821
> Add no112.org URLs

- lists/global.csv
Source: https://twitter.com/fring
> Removed dead websites

- lists/tr.csv
In this PR I added 3 news media websites which are at risk of getting blocked in Turkey over the next days, according to this news article: https://www.turkishminute.com/2022/02/21/untdown-begins-for-3-intl-media-outlets-in-turkey-to-get-licenses-or-face-ban/
I also fixed some formatting issues in the TR test list.
> Added news media websites to TR test list

- lists/ru.csv
Just added a news media website (New Times) that is reportedly blocked in Russia, according to this article: https://www.svoboda.org/a/v-rossii-nachali-blokirovatj-sayty-meduzy-bbc-i-deutsche-welle/31735721.html
Given the urgency of having this tested, I'm going to proceed with merging.
> Added New Times to RU test list

- lists/ru.csv
This PR adds a new BBC domain that has been set-up following the blocking of BBC in Russia.
> Added new BBC domain to RU test list

- lists/ua.csv
Community members requested that https://cip.gov.ua/ gets added to the UA test list to monitor for potential accessibility issues.
> Added gov site to UA test list

- lists/eg.csv
- lists/global.csv
Based on community feedback, I changed the category code of a URL in the global test list and added a URL to the EG test list which is reportedly blocked.
> Updates to Global and EG test lists

- lists/global.csv
In response to community updates (https://twitter.com/RimaSghaier/status/1509150505448222720), this PR adds Microsoft Teams to the global test list.
> Added Microsoft Teams to Global test list

- lists/global.csv
- lists/ir.csv
These sites are too risky to test in Iran, so we should remove them from
the lists
> Drop all .il domain from the IR and global test lists

- lists/global.csv
the URL no longer resolves, the A record has been removed
> Remove https://mitm.watch/

- lists/ru.csv
This PR adds romb.tv to the RU test list.
> Add Romb to RU list

- lists/de.csv
https://www.kjm-online.de/service/pressemitteilungen/meldung/kjm-beschliesst-sperrung-von-xhamster
> de.xhamster.com blocked by German ISPs

- lists/global.csv
to detect hidden censorship
there is 3 hostname but I added only two of them.
[full list test](https://run.ooni.io/nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%22https%3A%2F%2Fwww.goodreads.com%2F%22%2C%22https%3A%2F%2Fimages.gr-assets.com%2Fauthors%2F1198518558p2%2F23924.jpg%22%2C%22https%3A%2F%2Fs.gr-assets.com%2Frobots.txt%22%2C%22https%3A%2F%2Fi.gr-assets.com%2Frobots.txt%22%5D%7D&mv=1.2.0)
(blocked in Iran)
> add goodreads assets

- lists/global.csv
https://web.archive.org/web/20170121093443/http://www.pokerroom.com/
> Removed http://www.pokerroom.com/

- lists/global.csv
https://www.theguardian.com/technology/blog/2011/dec/16/goodbye-delicious-hello-pinboard-bookmarking-guardian
> Removed http://delicious.com/ & added https://pinboard.in/

- lists/global.csv
> Removed https://secure.proxpn.com/

- lists/global.csv
Focus changeover
https://web.archive.org/web/20130125055155/http://www.postcards-for-iran.org/
https://web.archive.org/web/20140212044203/http://www.postcards-for-iran.org/
> Removed http://www.postcards-for-iran.org/

- lists/global.csv
Focus changeover
https://web.archive.org/web/20180722110602/https://qibla.com/
https://web.archive.org/web/20200426032452/https://qibla.com/
> Removed https://qibla.com/

- lists/global.csv
https://web.archive.org/web/20220106215728/https://iwhc.org/
> Replaced https://iwhc.org/ with https://fosfeminista.org/

- lists/global.csv
> Removed http://www.proxyweb.net/

- lists/global.csv
> Removed http://www.kurtuluscephesi.com/

- lists/global.csv
> Removed https://www.monife.com/

- lists/global.csv
> Removed http://www.transparentgender.com/

- lists/global.csv
> Removed http://www3.iaisite.org/

- lists/global.csv
> Removed http://www.twistedinternet.com/

- lists/global.csv
> Removed http://www.ilhr.org/

- lists/global.csv
> Removed http://www.gamingday.com/

- lists/global.csv
This site is reportedly blocked in Algeria, but probably worth testing globally.
> Added GoFundMe to Global list

- lists/ru.csv
Thanks to the participants of the Vilnius OONI hackathon, this PR includes additional independent news media websites worth testing in Russia.
> Added independent media sites to RU list

- lists/cn.csv
- lists/global.csv
- lists/in.csv
This PR adds a few more social media sites to the Global test list (based on global rankings), addressing https://github.com/ooni/ooni.org/issues/608.
> Added social media sites to Global list

- lists/br.csv
A user mentioned to us that the political party changed name and
website. This diff updates to the new website.
> fix: pmdb.org.br -> www.mdb.org.br

- lists/global.csv
URLs related to Google Play, Instagram, WhatsApp, Yandex, Bing
[OONI Run link](https://run.ooni.io/nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%22https%3A%2F%2Fmmg.whatsapp.net%2Frobots.txt%22%2C%22https%3A%2F%2Fpps.whatsapp.net%2Frobots.txt%22%2C%22https%3A%2F%2Fdit.whatsapp.net%2Frobots.txt%22%2C%22https%3A%2F%2Fmedia-arn2-1.cdn.whatsapp.net%2Frobots.txt%22%2C%22https%3A%2F%2Fmedia.fevn1-1.fna.whatsapp.net%2Frobots.txt%22%2C%22https%3A%2F%2Fscontent-ams4-1.cdninstagram.com%2Ffavicon.ico%22%2C%22https%3A%2F%2Fstatic.xx.fbcdn.net%2Ffavicon.ico%22%2C%22https%3A%2F%2Fedge-mqtt.facebook.com%2Ffavicon.ico%22%2C%22https%3A%2F%2Fweb.facebook.com%2Frobots.txt%22%2C%22https%3A%2F%2Flookaside.facebook.com%2Frobots.txt%22%2C%22https%3A%2F%2Fstatic.cdninstagram.com%2Frobots.txt%22%2C%22https%3A …
> add URLs to detect hidden censorhsip 3\n

- lists/global.csv
medium.com is more of a general blogging platform.
> fix: category of medium.com

- lists/pl.csv
Netalitica researchers did amazing updates to the PL test list! <3
> Netalitica updates to PL test list

- lists/pl.csv
As part of merging Netalitica test list updates (https://github.com/citizenlab/test-lists/pull/1116) to the PL list, some other contributions by a community member (https://github.com/citizenlab/test-lists/commit/c6429e97234ec7f2c8ebbe1d3b44ff8855dfbeed, https://github.com/citizenlab/test-lists/commit/445ddd3a86b7955f62bc410dd6cf0e228e2f9c2f) got lost.
This PR re-adds those contributions to the PL test list. 
Note: I didn't re-add `ria.ru` and `lenta.ru` because they were re-added by Netalitica researchers.
> Update PL list

- lists/th.csv
> [th] forum.thaivisa.com -> aseannow.com

- lists/az.csv
- lists/ru.csv
- lists/tm.csv
- lists/uz.csv
Landing pages to advertise USAGM Onion Services and how to access them through Tor.
> Added Onion Launchpads

- lists/fr.csv
Hi, 
Here is an additional list of blocked domains in France (I removed `wearechange.org` because it is already in global)
> Adds more blocked websites in France

- lists/sa.csv
Added DAWN's website which is possible blocked in KSA
> Adding dawnmena.org to Saudi Arabia test list

- lists/eg.csv
Added DAWN's website which is possible blocked in Egypt.
> Adding dawnmena.org to Egypt test list

- lists/global.csv
- lists/my.csv
Updated MY test list with latest political parties websites, news media websites and websites found blocked in Malaysia. Also removed inactive websites which were down for a while.
> Updated my.csv

- lists/th.csv
They probably got banned recently
> [th] Add two soccer live streaming websites

- lists/th.csv
- United Thai National Party
- Donation page for 2023 election campaign of Move Forward Party
> [th] Update th.csv for 2023 General Election

- lists/global.csv
- lists/ve.csv
These are sites that OONI users chose to test, which aren't in the lists
> Add more URLs to the test-lists from mining OONI measurements

- lists/kg.csv
Following requests from community members.
> Add two news media sites to KG country list

- lists/global.csv
- lists/th.csv
Adding Benar News website to global list. Since the website is present in thai.csv adding a '/thai' suffix to track the localized version of the site.
> Add Benar News to Global list, Add '/thai' suffix

- lists/th.csv
- www.vote62.com - crowdsource election monitoring platform
> [th] Add www.vote62.com - election monitoring

- lists/th.csv
For election on 14 May and advanced voting on 7 May 2023:
General Election
https://boraservices.bora.dopa.go.th/election/enqelection/ 
Local election
https://stat.bora.dopa.go.th/Election/enqelectloc/
> [th] Add Voting Station Locator websites

- lists/th.csv
- https://wewatchthailand.org/
- https://www.electionwatchth.org/
- https://ectreport.com
> [th] Add We Watch and ECT report sites (Thai Election)

- lists/global.csv
xref: https://github.com/pypi/support/issues/2751
> Add python hosting to global.csv

- lists/global.csv
Adding https://njal.la/ to global.csv file.
> Add njalla to global.csv

- lists/br.csv
- lists/global.csv
Reverts citizenlab/test-lists#1310
> Revert "Contribution from test-lists.ooni.org"

- lists/gt.csv
Hi 
This pr add news media outlet No Ficcion. 
thanks
> Add news media outlet No Ficcion. 

- lists/be.csv
- lists/cn.csv
- lists/global.csv
IPFS gateways provide a range of content
> Track IPFS

- lists/my.csv
Added WeeChooKeong.com based on recent blocking (https://www.malaysianow.com/news/2023/07/25/another-site-critical-of-govt-blocked) and removed http://diversitymalaysia.org/ due to inactivity.
> Update iMAP test list

- lists/np.csv
TikTok is reported to be blocked in Nepal: https://www.bbc.com/news/business-67411535
> Add TikTok endpoints to np.csv

- lists/global.csv
See: https://support.mozilla.org/en-US/kb/canary-domain-use-application-dnsnet
> Add DoT firefox canary domain

- lists/ru.csv
Suspected to be blocked in Russia
> Add tor forum to ru list

- lists/global.csv
Last known active: https://web.archive.org/web/20210303064118/http://onlinedating.com/
> Removed http://www.onlinedating.com/

- lists/global.csv
https://web.archive.org/web/20140511073756/http://www.pokerpages.com:80/articles/archives/announce01.htm
> Removed http://www.pokerpages.com/

- lists/global.csv
> Removed http://www.warhammeronline.com/

- lists/global.csv
https://web.archive.org/web/20220213063133/http://www.nazi-lauck-nsdapao.com/
> Changed http://www.nazi-lauck-nsdapao.com/ into https://nsdapao.info/

- lists/global.csv
Changes Daily Stormer category from POLR to HATE.
_https://www.splcenter.org/fighting-hate/extremist-files/individual/andrew-anglin_
Changes ELF category from ENV to MILX.
_https://www.counterextremism.com/supremacy/earth-liberation-front_
> Updated Daily Stormer URL

- lists/global.csv
https://web.archive.org/web/20080516013827/http://www.ihf-hr.org/
> Removed http://www.ihf-hr.org/

- lists/global.csv
> Removed https://localcryptos.com/

- lists/global.csv
- lists/ru.csv
> Removed https://localbitcoins.com/

- lists/cl.csv
- Changes http://www.diarioelobservador.cl/ into https://www.observador.cl/ (https://web.archive.org/web/20210119110820/www.diarioelobservador.cl)
- Changes http://www.radiopolar.com/ into https://radiopolar.com/
> Updated cl.csv

- lists/global.csv
Adding s3 bucket that is rumored blocked in China, but possibly elsewhere too. Commonly used by circumvention tools for discovery.
> Add s3 bucket

- lists/ru.csv
This pull request includes extensive test list updates to the Russian test list by Roskomsvoboda (with a focus on the `NEWS` category), as part of collaborative research on media censorship in Russia.
> DRL FAA RU Test List Update

- lists/bf.csv
Add news websites ordered to be suspended since April 27th: https://twitter.com/sergedanielinfo/status/1784676862083399728?s=46
> Create a test list for BF

- lists/it.csv
Reportedly blocked in Italy.
https://gitlab.torproject.org/tpo/network-health/team/-/issues/92#note_3043653
> Add gate.io

- lists/fr.csv
This PR updates the FR list, removes some domains that do not exist anymore and adds domains recently blocked.
> Update FR list

- lists/it.csv
Reportedly blocked by PiracyShield
> Add drive.usercontent.google.com to italy list

- lists/ve.csv
This PR removes outdated sites from the ve.csv list. The deleted websites are either unavailable, abandoned, or completely irrelevant to Venezuela. It also updates several URLs to use HTTPS if supported.
These changes were reviewed by [VE sin Filtro](https://vesinfiltro.org). 
CC: @andresazp
> ve.csv - Delete outdated websites and update URLs to HTTPS

- lists/global.csv
Add new organization - reprouncensored.org
> Add reprouncensored

- lists/ph.csv
This is a follow-up PR of #1897 
- Removed https://lgbtbar.org/ (_National organization in the United States, irrelevant to ph.csv_)
- Removed https://www.facebook.com/giboteodoro (_since Facebook is already present in global list_)
- Removed https://www.facebook.com/Mochablogger/ (_since Facebook is already present in global list_)
- Removed http://www.arabtimesonline.com/ (_since_ `https` _is already present_)
> Follow-up update on ph.csv

- lists/in.csv
This pull request is a result of a two-day workshop hosted in collaboration with the Bachchao Project (https://thebachchaoproject.org/) for Indian researchers. As part of this workshop, researchers reviewed and updated 23 categories of websites: REL, HOST, NEWS, POLR, HUMR, COMM, FILE, MMED, SRCH, COMT, HACK, GAME, ANON, GMB, PUBH, ALDR, ENV, GOVT, XED, PORN, DATE, LGBT, MILX.
> Comprehensive update of IN test list

- lists/ua.csv
This pull request is created as a result of Netalitica's (https://netalitica.com/) work on updating the country-specific test lists for Ukraine.
> Netalitica's update of the UA test list
