citizenlab/test-lists

lists/global.csv

sci-hub.io replaced sci-hub.org.
This is a fix to pull request #63.

Fix the note for http://sci-hub.io/.

---

lists/jo.csv

The Temple Institute website is blocked on several ISPs in Jordan. I'm not sure if the `REL` category is correct, as this is a religious website, but it actually deals with propaganda and promotes the destruction of sacred sites in Jerusalem in order to build a new Jewish temple. In any case, it is blocked in Jordan.
See: https://www.templeinstitute.org

lists/jo.csv: Add Temple Institute to Jordanian block list

---

lists/pk.csv

Satire website Khabaristan Times has reportedly been blocked in Pakistan since 25th January 2017 (http://www.dawn.com/news/1311841). I've added this site (https://khabaristantimes.com/) to the Pakistani test list.

Added Khabaristan Times site to Pakistani test list

---

lists/eg.csv

Added the correct URLs for Signal Desktop testing please review to make sure specifying the port doesn't break anything you have before merge.  Signal desktop does TLS over port 80, 4433, and 8443 so we test all these as well as the server used to send attachments.
Also this might make more sense to move to the global list in the future but I think we should clean up that list before adding to it.

added proper Signal server URLs to .eg list

---

lists/ch.csv

c9c.net is DNS blocked by Swisscom.ch a larger ISP in Switzerland
```
markus@zoidberg:~$ nslookup c9c.net 195.186.1.111
Server:		195.186.1.111
Address:	195.186.1.111#53
Non-authoritative answer:
Name:	c9c.net
Address: 195.186.135.218
markus@zoidberg:~$ nslookup c9c.net 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53
Non-authoritative answer:
Name:	c9c.net
Address: 63.247.87.242
```
reason: `Access to this site is blocked due to a court order.`

add ch.csv with c9c.net

---

lists/eg.csv
lists/global.csv

Removed torproject.org from eg.csv as it exists in the global list;
Moved bridges.torproject.org there as well;
Added OONI related domains
Removed a couple of sites that are no longer published at the listed domain names.
Added a couple of more news sites as candidates for blocking in Egypt to eg.csv

Moved Tor domains to global, and added and refreshed others

---

lists/ua.csv

Download sites/home pages:
https://freeu.online/
https://freeu.zone/
(http versions currently 307 redirect to https)
Potential blocklist servers:
https://update.brwsrapi.com/blckd.json
https://update.mrbrwsr.com/blckd.json
https://update.savebrwsr.com/blckd.json
https://update.svbrwsr.com/blckd.json
https://update.updtapi.com/blckd.json
https://update.updtbrwsr.com/blckd.json
(The same domains also serve the actual downloads, e.g. freeu.exe. Also
versions without the "update." seem to work, but are not added to the
list.)
Canary URLs (we suspect that FreeU fetches these URLs as a check to see
if blocking is happening):
https://vk.com/ping.txt
https://ok.ru/google55e918a7d2970a76.html
Before 2017-05-25, these used http, not https.
More details here: https://bugs.torproject.org/22369

Add URLs related to the FreeU web browser to the UA list.

---

lists/tw.csv

fire.news is the political commentary site by pro-chinese-unification groups in Taiwan, mainly the New Party.
Relevant news of recent arrests of New Party members: http://www.taipeitimes.com/News/taiwan/archives/2017/12/23/2003684482

Add fire.news to TW list

---

lists/global.csv

This should be deleted as it's no longer active and we have no evidence of it being blocked based on OONI data in any country.
It was reported by a community member.

Remove 911lies.org

---

lists/global.csv

Reported by a community member.
See: https://en.wikipedia.org/w/index.php?title=Bloglines&oldid=795961988

Remove the defunct bloglines.com

---

lists/global.csv

GitHub hosts many projects that are prime targets for censorship. 
Note: GitHub is blocked in Clarksville-Montgomery County Tennessee (CMCSS) schools, which prompted me to add it to the master list.

Add GitHub to global list

---

lists/ir.csv

Handle.net is a provider of persistent identifiers that are used in academic and institutional repositories. Several users have told me hdl.handle.net links using both both HTTP and HTTPS are inaccessible in Iran.
Closes #322.

lists/ir.csv: Add hdl.handle.net

---

lists/global.csv

It seems like some are using this as a censorship circumvention strategy (ex. telegram).

Add dns.google.com to the global list

---

lists/lk.csv

Added NGO and social media websites from the [ 2017 Freedom on the Net Report](https://freedomhouse.org/report/freedom-net/2017/sri-lanka), URLs that [Groundviews reported](https://groundviews.org/2017/12/08/blocked-rti-requests-reveal-process-behind-blocking-of-websites-in-sri-lanka/) were blocked in December 2017, and other news media websites.

Update lk.csv 

---

lists/global.csv

This is pretty new, analogous to Google's and Cloudflare's: https://amphtml.wordpress.com/2018/09/19/introducing-bing-amp-viewer-and-bing-amp-cache/
Unclear whether this is blocked anywhere, as cdn.ampproject.com (Google) is reported to be in Egypt.
Incidentally, the existing entry https://amp.cloudflare.com/v0/amp-iframe-0.1.js is giving me 404 errors right now.

Add a bing-amp.com URL, for Microsoft's AMP cache.

---

lists/global.csv

These complement the existing https://dns.google.com/. For these new
ones, I added a path and query string that actually does a lookup for
www.example.com, rather than pointing at their landing page.
Besides their memorable IPv4 address, these services also have IPv6
addresses. But as far as I can tell, there are no existing URLs with
literal IPv6 addresses. Additional addresses, not added by this patch,
are:
Quad9
149.112.112.112
2620:fe::fe
2620:fe::9
Cloudflare
2606:4700:4700::1111
2606:4700:4700::1001
In lookup up these providers, I also found
https://cleanbrowsing.org/dnsoverhttps operating a public DNS over HTTPS
server.

Add Cloudflare and Quad9 DNS over HTTPS servers.

---

lists/de.csv

Personal tests and several unrelated sources report that sci-hub.tw is
blocked via DNS in networks of Vodafone at least since December 2017.
Sources:
- https://twitter.com/reinhardremfort/status/938688543572054016
- https://forum.golem.de/kommentare/internet/sci-hub-schwedischer-isp-blockt-elsevier-nach-blockieraufforderung/vodafone-wlan-hotspot-blockt-sci-hub.tw-ebenfalls/121776,5223229,5223229,read.html
- https://www.reddit.com/r/de/comments/8vr8vd/was_zur_h%C3%B6lle_l%C3%A4uft_bei_vodafone_schief/e1pt9yd/
- https://netzpolitik.org/2018/netzsperren-vodafone-muss-kinox-to-blockieren-und-kundendaten-speichern/#comment-2429563
- https://www.heise.de/forum/heise-online/News-Kommentare/Aus-Protest-Schwedischer-Provider-blockiert-Elsevier/In-Deutschland-sperrt-Vodafone-den-Zugriff-auf-Sci-Hub/ …

Add sci-hub.to to German list

---

lists/cn.csv
lists/ru.csv

Manually added by looking at the official GitHub repository for
government takedown requests at https://github.com/github/gov-takedowns
The URLs were mostly retrieved via following command (with GNU grep)
from within the cloned GitHub repository:
grep -roP --exclude-dir='.?*' 'https?://.*? ' . | sort | uniq | grep -v http://eais.rkn.gov.ru
URLs which lead to HTTP 404 errors, and thus cannot be categorized properly, were omitted (currently 5).
Although the Russian takedown requests announce that the offending URLs will be added to the "Unified register of the domain names, website references and network addresses that allow identifying websites containing information circulation of which is forbidden in the Russian Federation", only a few are listed there (mostly the newer ones from 2019). …

Add GitHub government takedown requests

---

lists/tr.csv

Today a court order from the Ankara 3rd Criminal Judgeship of Peace
(order no. 2019/5538) was leaked which lists 136 URLs that are ordered
to be blocked in Turkey.
Sources:
- https://bianet.org/system/uploads/1/files/attachments/000/002/687/original/Ankara_3rd_Criminal_Judgeship_of_Peace_2019-5538_Misc..pdf?1565091519
- https://bianet.org/bianet/ifade-ozgurlugu/211382-bianet-in-tum-icerigine-engelleme-karari
- https://umutgazetesi15.org/arsivler/18356
- https://www.zeit.de/politik/ausland/2019-08/internetzensur-tuerkei-oppositionelle-webseiten-sperrung
Only non-duplicate domains and working URLs were added.

Add some URLs from Turkish court order

---

lists/kr.csv

Women on Web (abortion site) is blocked in South Korea and so they encourage women to visit this site instead: http://www.abortion-korea.org/
I have therefore added it to the KR test list as part of this PR to check whether it's blocked too.
For reference: https://www.womenonwaves.org/en/page/4599/women-on-web-website-is-blocked

Added abortion site to KR test list

---

lists/eg.csv
lists/sa.csv
lists/ye.csv

Aljazeera domains (aljazeera.com & aljazeera.net) have been added to the global test list (#510), which means they shouldn't be included in country lists as well (the CI checks won't pass if duplicate URLs are included across test lists).
I have therefore opened this PR to remove aljazeera domains from local test lists.
@sneft Merging this PR is a prerequisite to merging #510.

Removed Aljazeera from local lists

---

lists/global.csv

Aljazeera appears to have 2 domains: aljazeera.net & aljazeera.com. 
As part of this PR, I added aljazeera.com to the global test list and fixed the URL for aljazeera.net.

Added Aljazeera to global list

---

lists/fr.csv

Hi,
Here are a few more websites interesting to track for France :
* https://libgen.is/ is an website giving free access to scientific research, it was blocked by main French ISP in April 2019 ([ref](https://www.numerama.com/sciences/477218-sci-hub-et-libgen-luttent-pour-la-diffusion-gratuite-du-savoir-scientifique-la-france-ordonne-leur-blocage.html))
* https://grenoble.indymedia.org/ and https://nantes.indymedia.org/ are independent media websites that were threatened to be blocked by the police in January 2019 ([ref](https://nantes.indymedia.org/articles/44313))
Let me know if this PR is okay

Add more sites to the FR list

---

lists/mn.csv

Minor fix - Header for the mongolia list was inconsistent with the other headers
date_aded != date_added
The linter should probably be added to look for this, though the rest of the repo is fine.

mongolia list header typo

---

lists/es.csv

These domains were banned using the services of allot.com the day of the General Strike of 18th of October.
The strike demanded working rights, but mainly protested against the jail sentence of the leaders of catalan interdependentist parties, started at 2017 after the prohibited independence referendum.
Tsunami democratic is the name of a hidden group of activists that gained the support of indenpendentist parties and that succeed at its call for blocking the Barcelona airport the 14th of October (the monday before the censorship) https://www.theguardian.com/world/2019/oct/18/new-generation-new-tactics-the-changing-face-of-catalan-protests
The kind of censorship appears to be different from that of October 2017: Then it was with DNS hijack, today DNS appears to stay ok, but with help of …

Add new censored domains in Spain at 18th Oct 2019

---

lists/ni.csv

There are no URLs in the Nicaragua list (.ni) list, I believe it should either have a URL added or the list should be removed entirely (this PR).  If this is accepted I can add this logic to the linter as well (that lists should have at least a single URL)
Cheers,
Jakub

Removed blank Nicaragua list (.ni) 

---

lists/br.csv

São Paulo Court of Justice website blocking order on September 12, 2019:
https://web.archive.org/save/https://www.jusbrasil.com.br/diarios/261303463/djsp-judicial-1a-instancia-capital-12-09-2019-pg-1166

Add websites issued to be blocked by court in Brasil

---

lists/pk.csv

As slate.com is an internationally relevant media website (which may be blocked in more countries, beyond Pakistan), I have removed this site from the PK test list and opened a separate PR to add it to the global test list: https://github.com/citizenlab/test-lists/pull/556
Merging this PR is a prerequisite to merging #556.

Remove Slate from PK test list

---

lists/global.csv

Slate is an internationally popular media website, yet it wasn't included in the global test list. It's currently blocked in Pakistan and may be blocked in other countries as well, which is why I opened this PR to add it to the global test list.

Add Slate to global test list

---

lists/eg.csv

I have removed briarproject.org from the EG test list so that it can be included in the Global test list instead (since we don't support duplicate URLs between the global and country-specific test lists). 
By merging this PR, we are unblocking https://github.com/citizenlab/test-lists/pull/589.

Removed Briar from EG test list

---

lists/ve.csv

This PR includes the 3 sites that are now reportedly blocked in Venezuela: https://vesinfiltro.com/noticias/bloqueado_portal_coronavirus_AN
Two of these blocked sites are information portals on the coronavirus pandemic.

Coronavirus update to VE list

---

lists/global.csv

I've updated the global test list to include all the other coronavirus-related websites I could find. More specifically, these are mainly global data maps that track the spread of COVID-19 worldwide and are therefore of global relevance. I have added "coronavirus" in the notes to enable targeted data analysis afterwards.

Coronavirus sites added to global list

---

lists/global.csv

Add coronavirus sites, bit.ly and discord that have been reported as
blocked in Portugal.
References:
- https://revolucaodosbytes.pt/a-nos-e-o-bloqueio-de-dominios-legitimos/
- https://revolucaodosbytes.pt/nos-bloqueia-bit-ly/

Add coronavirus sites, bit.ly and discord

---

lists/uy.csv

I had some analysis break because date_added was a date in the future (year 3027) in one case, this fixes that (based on surrounding date)  I guess the linter should make sure this doesn't happen but not a big deal.

fixed future/impossible date_added from uy list

---

lists/eg.csv

These two sites were reported to be ordered blocked in Egypt for sharing COVID-19 related disinformation.

EG: +2 News sites reported to be blocked for sharing COVID disinfo

---

lists/global.csv

This PR adds letsencrypt.org to the global test list, as well http://ocsp.int-x3.letsencrypt.org/ which is reportedly blocked in China, but probably worth testing globally.

Added Let's Encrypt to global test list

---

lists/br.csv
lists/global.csv

Hi,
It is my first contribution to Citizen Lab's test lists. I have added three News Media sources to the Brazilian file, namely:
- [economia.uol.com.br](https://economia.uol.com.br)
- [noticias.uol.com.br](https://noticias.uol.com.br)
- [theintercept.com/brasil/](https://theintercept.com/brasil/)
The first two are the economy-related website and the general-news website from major local UOL portal. The third one is the pt-br branch of The Intercept, run in Brazil by Glenn Greenwald.
Based on the news coverage by those websites and recent statements from Brazil's president and members of his family, I think those three websites should be added to the br.csv file.
Thank you.

Added 3 News Media sources to br.csv

---

lists/global.csv

We run a privacy-centric blogging platform called [Write.as](https://write.as) that's used all over the world. Considering our mission to give writers anonymity, and some odd DNS errors recently [reported](https://writing.exchange/@matt/104195516669277207) by users in Indonesia, it looks like we're seeing some kind of censorship happening there. It would be great to test for that.

Add Write.as

---

lists/cn.csv

This PR includes updates to the CN test list based on URLs shared by OTF Fellow, Phong. These URLs seem to be blocked in CN.

Added blocked sites to CN test list

---

lists/global.csv

Used in Google Go.
https://developers.google.com/search/docs/advanced/mobile/web-light?hl=en#see-the-web-light-version-of-a-web-page
Blocked in Iran. ( AS197207 is also Iran)
https://explorer.ooni.org/search?until=2020-12-01&since=2020-11-01&domain=googleweblight.com

add googleweblight to global.csv

---

lists/global.csv

I updated the global test list to add 2 espiv domains. ESPIV provide emails, mailing lists, blogging platforms, and forums -- all of which are run by an autonomous collective and these services are often used by human rights activists. 
Part of the motivation to add this now to the global test list is also the fact that it's being reported that ESPIV services may be blocked in Spain and Chile, and it may be interesting to test them globally on an ongoing basis.

Added ESPIV to global test list

---

lists/cn.csv

I am proxying this update for Phong (OTF) but his work seems to indicate these six domains are being DNS poisioned within China.  Hoping to see the breadth of this behaviour with this update.
Cheers,
Jakub

Adding potentially blocked china covid urls

---

lists/global.csv

Seems on-topic given that other censorship-resistant suTLD's such as Tor, DNS providers such as OpenDNS, and other blockchain projects such as Bitcoin are on the list.  Also seems sufficiently non-redundant given that I don't see any other decentralized DNS-like naming systems on the list.  I got a user report alleging that it was blocked in Belarus in January 2021 (I haven't been able to verify the accuracy of that report).
I initially reached out on IRC; @agrabeli recommended that I open a PR here.

Add Namecoin.org

---

lists/hk.csv

- hkleaks.info and hkchronicles.com are both the same site. They're closer to political criticism than they are to a news source.
- Four days ago the administrator of the site created a *third* domain pointing to the same site, blockedbyhk.com.
- The first two domains were both included in the first-known instance of using the NSL to block websites in Hong Kong.
- The third domain, blockedbyhk.com, as of the date of this PR remains unblocked.

Update Hong Kong list to account for developments.

---

lists/ng.csv

I've updated the NG test list to include a media website that's reportedly blocked.
For reference:
https://twitter.com/GazetteNGR/status/1354446025000415246
https://guardian.ng/news/clampdown-on-peoples-gazette-as-telcos-block-access-to-news-website/
http://saharareporters.com/2021/01/28/nigerian-government-blocks-peoples-gazette-website-over-critical-media-reports

Updated NG test list

---

lists/mm.csv

Added tests for Signal messenger as stop-gap measure until the [signal messenger tests](https://github.com/ooni/probe-cli/pull/230/files#diff-ed1b4f0013a12402e0f5ced63481629b1606b49c75d2e4a91d7081df31ebafa4R112) are implemented in the new release.

Add tests for Signal Messenger

---

lists/global.csv

Add upload.wikimedia.org that hosts media files for the Wikimedia Foundation to the list.

Update lists/global.csv to add a Wikimedia project

---

lists/eg.csv

NordVPN should be included in the global test list (to get tested globally). To avoid duplication of URLs (and since I'm trying to add it to the global test list: https://github.com/citizenlab/test-lists/pull/734), I am opening this PR to remove it from the EG test list.

Removed NordVPN from EG list

---

lists/global.csv

Add Greenhost main site, a provider focussing on digital rights and privacy to the global list

Add provider to global list

---

lists/mm.csv

I'm updating the MM test list to include https://iimm.un.org/ which is reportedly blocked in Myanmar.

Updated MM test list

---

lists/global.csv

Website is down for more than a year. Domain is parked.

Remove twilight.ws

---

lists/be.csv

ipfs.io reported as blocked in Belgium
https://web.archive.org/web/20210401073940/https://discuss.ipfs.io/t/ipfs-blocked-in-belgium/7930

Add ipfs.io to BE list

---

lists/global.csv

It's failing globally: https://explorer.ooni.org/search?until=2021-04-07&since=2021-03-07&domain=www.meaphone.com

Remove parked domain www.meaphone.com

---

lists/global.csv

Probably the domain has a new owner now. It seems that for a year it was entirely down and now it's either redirecting to a porn site or entirely inaccessible:
https://web.archive.org/web/20210901000000*/www.sexualhealth.com
https://explorer.ooni.org/search?until=2021-04-07&since=2021-03-07&domain=www.sexualhealth.com

Remove www.sexualhealth.com

---

lists/pl.csv

Those seem to be control domains used by them. Discovered through own analysis of the list.

Add CTRL for PL CERT lista ostrzezen

---

lists/global.csv

Website is down. Was last seen in 2016: https://web.archive.org/web/20160830114545/http://www.connotea.org/
> Connotea discontinued service on March 12, 2013.

Remove www.connotea.org

---

lists/global.csv

Last content on the website was from 2013, so it's not surprising that it's gone: https://web.archive.org/web/20200721180116/http://international.ohmynews.com/

Remove international.ohmynews.com

---

lists/global.csv

Down since 2019: https://web.archive.org/web/20190102003828/http://www.arabhra.org/

Remove www.arabhra.org

---

lists/global.csv

Down since 2017: https://web.archive.org/web/20170907040058/http://www.familiesaretalking.org/

Remove www.familiesaretalking.org

---

lists/global.csv

Down since 2017: https://web.archive.org/web/20170916084953/http://efindlove.com/. Now parked.

Remove www.efindlove.com

---

lists/global.csv

Domain is parked. Has been down for a long time.

Remove translation.langenberg.com

---

lists/global.csv

Parked at least since 2019: https://web.archive.org/web/20190114201444/http://www.crackz.ws/

Remove www.crackz.ws

---

lists/it.csv

Blocked in Italy, see: https://roma.corriere.it/notizie/cronaca/21_giugno_07/roma-istruzioni-ragazzi-il-suicidio-oscurato-sito-internet-7e7911ce-c769-11eb-9c4c-4cf000dece4f.shtml

Add sanctioned-suicide.org to it.csv

---

lists/cu.csv
lists/ve.csv

A site (https://cazadoresdefakenews.info/) which tracks fake news in Venezuela (through a crowdsourcing community) is reportedly blocked in Cuba (see: https://twitter.com/norges14/status/1428385486322667530).
I have added this site to both the CU and VE test lists as part of this PR.

Updated CU and VE test lists

---

lists/global.csv

And add two addresses related to Medium.
(`miro.medium.com` and `external-content.duckduckgo.com` are blocked in Iran.)
[OONI Run](https://run.ooni.io/nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%22https%3A%2F%2Fwebcache.googleusercontent.com%2Frobots.txt%22%2C%22https%3A%2F%2Fyandexwebcache.net%2Frobots.txt%22%2C%22https%3A%2F%2Fcc.bingj.com%2Fcache.aspx%3Fq%3Dnothing%22%2C%22https%3A%2F%2Fencrypted-tbn0.gstatic.com%2Frobots.txt%22%2C%22https%3A%2F%2Fim0-tub-com.yandex.net%2Fi%3Fid%3D462f375c96139f1e41d919b44be2d780%26n%3D13%26exp%3D1%22%2C%22https%3A%2F%2Fth.bing.com%2Fth%2Fid%2FOIP.YnpdokcN_OQYn3n41AlqZAHaEe%3Fw%3D250%26h%3D180%26c%3D7%26o%3D5%26pid%3D1.7%22%2C%22https%3A%2F%2Fexternal-content.duckduckgo.com%2Frobots.txt%22%2C%22https%3A%2F%2Fmiro.medium.com%2Frobots.txt%22%2C%22h …

add image and web cache related to search engines

---

lists/id.csv

Added International rivers that is blocked in Indonesia. 
Perhaps related to new internet regulation
https://www.hrw.org/news/2021/05/21/indonesia-suspend-revise-new-internet-regulation

International Rivers blocked in Indonesia

---

lists/global.csv

OSSRH Maven Central is the default library repository for Java and Android projects.  It is a massive collection of open source Java libraries, including a number of circumvention tools.  It requires HTTPS so it could be a candidate for being fully blocked in order block access to specific packages that are hosted there.  It could be consdered something like GitHub or Bitbucket.

include OSSRH Maven Central in global list

---

lists/in.csv

piratebay.live is proxy site for piratebay.org that has been blocked in india for many years, just noticed it is not in the list so updating it.

Update in.csv (added piratebay.live to the list)

---

lists/th.csv

A Japanese website that reported to require a Chinese Internet Content Provider license in other to view from Thailand. 
This is to close #866 (see details there)

Add https://www.dlsite.com/ to TH list

---

lists/kr.csv

This PR adds https://womenonweb.kr/ which is reportedly blocked in South Korea.
We already know that the international version of Women on Web is blocked in South Korea: https://ooni.org/post/2019-blocking-abortion-rights-websites-women-on-waves-web/#south-korea

Added Korean Women on Web to KR test list

---

lists/ru.csv

Roskomnadzor requested Wikimedia to take down the article on Russia's invasion of Ukraine on March 1, 2022, and threatened to block access to Wikipedia, too. Further, at least on Wikipedia editor who has been working on the article about the invasion has been arrested. 
Relevant links:
https://www.reuters.com/world/europe/moscow-threatens-block-russian-language-wikipedia-over-invasion-article-2022-03-02/
https://www.theverge.com/2022/3/11/22973293/wikipedia-editor-russia-belarus-ukraine

Add link to articles about Russia's invasion of Ukraine on Wikipedia

---

lists/global.csv

BackTrack Linux is now Kali Linux (Since 2013) [For more information, kindly go to https://www.backtrack-linux.org/]
http://hotmail.msn.com/ & http://www.hotmail.com/ both redirects to https://outlook.live.com/ which is already present in the list
Removed duplicate URLs of BBC News and Spiegel. Removed Rise Broadband as I pointed out on PR #857

Updated links and remove duplicates in global.csv

---

lists/global.csv

- https://en.wikipedia.org/wiki/43_Things (The 43 Things website went offline on New Years Day, 2015.)
- https://news.yahoo.com/yahoo-shuts-down-internet-relic-182218531.html (Altavista shut down on July 8, 2013)
- https://avoiceformen.com/featured/angry-harry-passes-away/ (Website now 404 Not Found)
- Updated DailyStormer website

Removed dead websites

---

lists/global.csv

Added global test for starlink.com, already banned in some countries due to its role in censorship circumvention and emergency internet access. Currently not tested.

Added global test for starlink.com

---

lists/global.csv

Few corrections to stale URLs and Websites that are MIA. 
https://black.riseup.net/ Bitmask Black VPN is no longer available here. 
https://download.i2p2.de/ The download subdomain has moved to download page, this now points to fdroid external site.
http://redjohn.net/, RedJohn remailer website is no longer available.

Global List Cleanup

---

lists/global.csv

https://www.cbc.ca/news/politics/federal-budget-folds-cida-into-foreign-affairs-1.1412948

Replaced http://www.acdi-cida.gc.ca/ with https://www.international.gc.ca/

---

lists/global.csv

https://theoutline.com/post/2549/rotten-com-is-offline

Removed http://www.rotten.com/

---

lists/my.csv

Found that https://www.answering-islam.org/ is more likely a religion-related website, rather than a news media site. Could this be a possible miscategorisation?

Possible miscategorisation of www.answering-islam.org in MY list?

---

lists/by.csv

My friend's "homepage" https://politzek.me/friends/ekalinovsky is not accessible from there. The `http` version of the page looks like this.

Recent ban of the list of political prisoners in Belarus

---

lists/ph.csv

This PR is a follow-up to https://github.com/citizenlab/test-lists/pull/1022, adding a few more URLs reportedly blocked in the Philippines.

Updated PH list

---

lists/in.csv

It appears the website has moved to a new URL in Feb 2022. Confirmed using internet archive https://web.archive.org/web/20220000000000*/bspindia.org

update BSP political party website URL

---

lists/az.csv

We're receiving reports that the TikTok app may have been blocked in Azerbaijan today. This PR therefore adds TikTok endpoints to the AZ test list. 
I've refrained from adding these endpoints to the Global test list, as it's quite a long list of endpoints (whereas the AZ list -- where the blocking is being reported -- is short). We could potentially remove these endpoints from the AZ list (and potentially add some or all of them to the Global list) once we've collected enough data over the next weeks to investigate this case.

Added TikTok endpoints to AZ test list

---

lists/global.csv

Removing expired domain matrimony.org from Global list. 
https://explorer.ooni.org/chart/mat?test_name=web_connectivity&input=http%3A%2F%2Fwww.matrimony.org%2F&since=2022-09-01&until=2022-10-01&axis_x=measurement_start_day

Removing matrimony.org from Global

---

lists/kh.csv

Removing expired news.kqube.net from KH list.

Remove news.kqube.net from KH

---

lists/global.csv

Remove inactive website www.infowar-monitor.net from global lists.
https://explorer.ooni.org/chart/mat?test_name=web_connectivity&input=http%3A%2F%2Fwww.infowar-monitor.net%2F&since=2022-09-01&until=2022-10-01&axis_x=measurement_start_day

Remove infowar-monitor.net from Global

---

lists/global.csv

Removing inactive website www.asstr.org from global list. 
https://explorer.ooni.org/chart/mat?test_name=web_connectivity&input=http%3A%2F%2Fwww.asstr.org%2F&since=2022-09-01&until=2022-10-01&axis_x=measurement_start_day

Remove asstr.org from Global

---

lists/global.csv

Remove inaccessible and offline website www.hivandhepatitis.com from Global
https://explorer.ooni.org/chart/mat?test_name=web_connectivity&input=http%3A%2F%2Fwww.hivandhepatitis.com%2F&since=2022-09-01&until=2022-10-01&axis_x=measurement_start_day

Remove www.hivandhepatitis.com from Global

---

lists/global.csv

The coronavirus-map.com website is no longer active. Suggest removing it from measurements.

Remove defunct coronavirus-map.com

---

lists/gh.csv
lists/global.csv

Hosting and blogging platform 150m.com is currently not online for the last year or so. propose removing this from our test lists. 
/cc @sloncocs @agrabeli 
https://explorer.ooni.org/chart/mat?test_name=web_connectivity&input=http%3A%2F%2Fwww.150m.com&since=2021-10-12&until=2022-10-12&axis_x=measurement_start_day

Removing 150m.com and ecotours.150m.com

---

lists/ir.csv

This was supposed to be testing resolution of the hdl.handle.net do- main itself, not what the Handle link resolves to (Handles are like DOIs, where a persistent identifier points to a resource on another domain). We had a case of hdl.handle.net being blocked in Iran (not sure if still the case).
This test was erroneously updated to point to the resolved resource (I suspect someone used a script to update the list, because the Handle service would have returned an HTTP redirect). Furthermore, a trailing slash on this URL is not even valid (returns HTTP 404).
See: https://github.com/citizenlab/test-lists/pull/323
See: 34cac1b5b881404faf21ee9bf11f33945bd77129

lists/ir.csv: fix handle link

---

lists/it.csv

This diff deletes a bunch of domains that we found to be parked or nonexisting a while ago when testing web connectivity.
All these domains are part of the Italian test list.
They all have some residual censorship, but we've been favouring existing websites recently, so I think this diff makes sense.
Closes https://github.com/ooni/probe/issues/2316
Closes https://github.com/ooni/probe/issues/2315
Closes https://github.com/ooni/probe/issues/2314
Closes https://github.com/ooni/probe/issues/2312
Closes https://github.com/ooni/probe/issues/2302
Closes https://github.com/ooni/probe/issues/2308
Closes https://github.com/ooni/probe/issues/2304
Closes https://github.com/ooni/probe/issues/2310

chore(it.csv): zap parked/nonexisting domains

---

lists/ru.csv

This PR adds a Ukrainian news media site (https://www.epravda.com.ua/) that is reportedly blocked in Russia (https://roskomsvoboda.org/post/hromadske-blocked/).

Add UA blocked media to RU list

---

scripts/lint-lists.py

Allows the script to process non-latin characters on Windows, which defaults to cp1252

Specify utf-8 encoding when loading csv's in lint-lists.py

---

lists/kh.csv

Removing defunct CNRP7 domain name. 
Removing RFA.org which is already in Global list.

Removed defunt CNRP7 and RFA entry

---

lists/global.csv

These are already being tested as part of the tor reachability test. No need to duplicate coverage.

Drop tor directory authorities from global list

---

lists/global.csv

MuWire was a file sharing program that used the I2P network. However, the main developer gave up development and his work on I2P in general for personal reasons. It seems he could not find a successor / maintainer for the project.
Both the website and the seed/bootstrap servers for MuWire are dead.
see https://www.reddit.com/r/i2p/comments/zs1x5j/muwire_is_down/ and https://www.reddit.com/r/i2p/comments/112fmb9/muwire_shutdown/

Global: Remove MuWire

---

lists/global.csv

As announced in https://tails.net/news/new_domain/index.en.html, Tails now has its own domain.

Update tails website

---

lists/global.csv

jabber.ru was the victim of a MitM attack (see https://notes.valdikss.org.ru/jabber.ru-mitm/). Furthermore, some ISPs tend to block Russian sites (I know this from German universities, for example). I would therefore find it very interesting to see to what extent jabber.ru is also blocked.

Add jabber.ru

---

lists/kz.csv
scripts/lint-lists.py

This adds a check for an invalid header and fixes that KZ list which was malformed since: https://github.com/citizenlab/test-lists/commit/e96c7169fe147419e6e0d40ed92ae7fc90ababb1

Add check for invalid header

---

lists/global.csv

Dead link. Last known active: https://web.archive.org/web/20221128122611/http://solicitorsfromhell.com/

Removed http://www.solicitorsfromhell.com/

---

lists/global.csv

Focus changeover. No known new/alternative website
https://web.archive.org/web/20221014224711/https://www.jewwatch.com/

Removed http://www.jewwatch.com/

---

lists/global.csv

Dead link. No known new or alternative website.

Removed http://www.harkatulmujahideen.org/

---

lists/global.csv

Focus changeover
Start-2013: https://web.archive.org/web/20130601054453/http://earth-liberation-front.org/
2014-2015: https://web.archive.org/web/20131204020900/http://earth-liberation-front.org/
2015-2016: https://web.archive.org/web/20150910004857/http://earth-liberation-front.org/
2016-2018: https://web.archive.org/web/20161220045654/http://earth-liberation-front.org/
2018-2020: https://web.archive.org/web/20181109004509/http://earth-liberation-front.org/
2020-Present: https://web.archive.org/web/20200923171836/http://earth-liberation-front.org/

Removed http://earth-liberation-front.org/

---

lists/global.csv

Dead link. I looked at the [Wayback Machine](https://web.archive.org/) and there is a large gap of archiving in this site, it is last known working on 2014.

Removed http://triviasecurity.net/

---

lists/global.csv

comohacerseunaborto.com is parked free, courtesy of GoDaddy.com

Removed http://comohacerseunaborto.com/

---

lists/global.csv

Last known active: http://web.archive.org/web/20090429065456/http://www.thehacktivist.com/

Removed http://www.thehacktivist.com/

---

lists/global.csv

securitytracker.com is parked free, courtesy of GoDaddy.com

Removed http://www.securitytracker.com/

---

lists/global.csv

As noted by https://github.com/ooni/probe/issues/2329, we cannot access http://www.jsf.mil/ but we can access https://www.jsf.mil/.
See also https://explorer.ooni.org/chart/mat?since=2023-12-26&until=2024-01-26&time_grain=day&axis_x=measurement_start_day&test_name=web_connectivity&domain=www.jsf.mil
Closes https://github.com/ooni/probe/issues/2329.

fix(www.jsf.mil): http => https

---

lists/global.csv

Dead link. Its alternative website: http://videoshub.com/, is also not working.
https://en.wikipedia.org/wiki/Metacafe

Removed http://www.metacafe.com/

---

lists/global.csv
lists/id.csv

Focus changeover. No known new or alternative site of People's Movement for Human Rights Learning.
Last known active: https://web.archive.org/web/20220913031524/http://pdhre.org/

Removed http://www.pdhre.org/

---

lists/global.csv

Domain expired. No known new or alternative website.
https://web.archive.org/web/20230607065819/http://www.ruf-ch.org/

Removed http://www.ruf-ch.org/

---

lists/global.csv

Dead link. No known new or alternative site. Last known active: https://web.archive.org/web/20210823060903/http://www.hrusa.org/

Removed http://www.hrusa.org/

---

lists/global.csv

Dead link. No known new or alternative website of Ontario Consultants on Religious Tolerance.

Removed http://www.religioustolerance.org/

---

lists/global.csv

**Removed**
- https://nssac.bii.virginia.edu/covid-19/dashboard/ _(404 Not Found)_
- https://google.org/crisisresponse/covid19-map _(Discontinued: https://web.archive.org/web/20210712054031/google.org/crisisresponse/covid19-map)_
- https://www.bing.com/covid _(Discontinued: https://web.archive.org/web/20230414050847/https://www.bing.com/covid)_
- https://www.cdc.gov/coronavirus/2019-ncov/cases-updates/world-map.html _(Page Not Found)_
**Updated**
- https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6 => https://gisanddata.maps.arcgis.com/apps/dashboards/bda7594740fd40299423467b48e9ecf6
- https://www.projectbaseline.com/study/covid-19/ => https://www.projectbaseline.com/studies/covid-research/
- …

Removed defunct Covid-19 related websites

---

lists/th.csv

- Remove JD https://www.jd.co.th/ - no longer in operation, URL inaccessible, no history of blocking
- "JD Central to end Thai operations on March 3" (31 Jan 2023) https://www.bangkokpost.com/business/general/2494934/jd-central-to-end-thai-operations-on-march-3 
- Remove Robinson https://www.robinson.co.th/ - no longer in operation in its previous form (now a sub-brand within Central department store website), URL inaccessible, no history of blocking
- "CRC Announces Strategic Move, Combining the Strengths of Central and Robinson to Benefit Thai Customers" (17 Sep 2020) https://www.centralgroup.com/en/updates/corporate-news/460/crc-announces-strategic-move-combining-the-strengths-of-central-and-robinson-to-benefit-thai-customers 
- Remove BEC Tero Radio http://www.becteroradio.com/ - no …

[th] - Remove JD, Robinson, BEC-Tero Radio

---

lists/global.csv

Dead link. Last known active: https://web.archive.org/web/20221201110549/http://mywebcalls.com/
Also, replaced `http://www.warchild.org/` with `https://www.warchild.net/`

Removed http://www.mywebcalls.com/

---

lists/global.csv

Dead link. Last known active: https://web.archive.org/web/20230623180301/https://sci.hubg.org/

Removed https://sci.hubg.org/

---

lists/global.csv

https://web.archive.org/web/20230123190215/https://www.getrevue.co/
Also, replaced `https://www.csidonline.org/` with `https://csid-online.org/`

Removed https://www.getrevue.co/

---

lists/global.csv

Focus changeover. No known new or alternative site. Last known active: https://web.archive.org/web/20220815025951/https://occupystreams.org/

Removed https://occupystreams.org/

---

lists/ae.csv
lists/global.csv

Dead link. No known new or alternative website of NetZooLa. Last known active: https://web.archive.org/web/20200220234831/https://www.netzoola.com/
Callserve had migrated to Vyke: https://web.archive.org/web/20110613125549/http://www.callserve.com/Homepage.asp

Removed http://www.netzoola.com/

---

lists/fr.csv

Hi,
A recent decision by the court of appeal in France has asked ISPs to block 4 pornographic websites : TuKif, xHamster, MrSexe, and IciPorno, see https://www.euronews.com/next/2024/10/17/foreign-porn-websites-blocked-in-france-for-lack-of-age-control-checks
Here is a PR to adds 3 of them, xhamster is already in the Global list.
Let me know if you have any questions

Adds 3 pornographic websites to the fr list

---

lists/fr.csv

Hi everyone,
This PR adds more websites blocked in France:
* For unlawful online gambling (see details [here](https://censxres.fr/administrative/jeux-en-ligne/))
* Pornographic website
* Website blocked for frauds, see here https://signal.conso.gouv.fr/fr/actualites/deux-sites-frauduleux-bloques
* Smotrim is [a russian TV platform](https://en.wikipedia.org/wiki/Smotrim) that now host Russia 1 (which is supposed to be blocked in Europe due to the Council of the European Union

Adding more domains supposed to be blocked in France

---

lists/global.csv

Cloudflare IPFS gateways are discontinued: https://blog.cloudflare.com/cloudflares-public-ipfs-gateways-and-supporting-interplanetary-shipyard/

Remove cf ipfs gateways
